### ISSUE TITLE
aws_security_token is redundant

### ISSUE THREAD

**Issue by stewarda** [trueaccord/aws-saml-broker#1]
Hey guys. This tool has been very useful.
Just wanted to comment that I don't think you need 'aws_security_token' since it references the session token and is therefore redundant.

FORMATS = {
        'awscli': ('text/plain', lambda c: """[default]
 Will expire on %(expiration)s
aws_access_key_id = %(aws_access_key_id)s
aws_secret_access_key = %(aws_secret_access_key)s
aws_security_token = %(aws_session_token)s
aws_session_token = %(aws_session_token)s""" % c),
        'json': ('application/json', lambda c: json.dumps(c, indent=4))
        }

**Comment by thesamet** [comment]
Glad to hear you have found it useful! I can't remember at this point, but I think that we had various versions of AWS SDKs [1] wanting it to be under a different name, so we ended up with both.

If this causes any issue, feel free to re-open and I'll examine further. Thanks for reporting this!

[1] https://github.com/boto/botocore/blob/c76553d3158b083d818f88c898d8f6d7918478fd/botocore/credentials.py#L260-262

**Comment by stewarda** [comment]
Thanks a lot, I'll be working on this again later this week and will reopen if necessary!
